"""Bundle a tuned config + its engine into a single self-contained main.py.

    python -m ml.export_main --engine v7 ml/artifacts/phase1/best.json -o main_ml.py
    python -m ml.export_main --engine legacy ml/artifacts/phase2/best.json -o main_ml.py

Both engines only import stdlib (``math``, ``collections``), so the output is a
drop-in Kaggle submission: one file, an ``agent(obs)`` at module scope, the same
top-level try/except -> all-PASS fallback the builder already has.

``--engine v7`` bundles ``ml/engine_v7.py`` (the faithful ``main.py`` fork) and
is the one to ship. ``--engine legacy`` bundles ``ml/engine.py``.

ALWAYS gate the output with ``python test.py --candidate main_ml.py --incumbent
main.py --games 40`` (+ ``--gate``) and a real ladder submission before
overwriting main.py.
"""
from __future__ import annotations

import argparse
import json
import os

_HERE = os.path.dirname(os.path.abspath(__file__))

_ENGINES = {
    "v7": {
        "src": os.path.join(_HERE, "engine_v7.py"),
        "builder": "build_agent_v7",
        "spec": "ml.spec_v7",
        "default": "default_params_v7",
        "to_config": "params_to_config_v7",
    },
    "legacy": {
        "src": os.path.join(_HERE, "engine.py"),
        "builder": "build_agent",
        "spec": "ml.spec",
        "default": "default_params",
        "to_config": "params_to_config",
    },
}


def build(params: dict, engine: str = "v7") -> str:
    e = _ENGINES[engine]
    mod = __import__(e["spec"], fromlist=[e["default"], e["to_config"]])
    cfg = getattr(mod, e["to_config"])(params)
    src = open(e["src"], encoding="utf-8").read()
    # engine_v7.py starts with `from __future__ import annotations`, which must be
    # the first statement in the file -- keep the header a comment block only.
    header = (
        "# AUTO-GENERATED by ml/export_main.py -- do not hand-edit.\n"
        f"# Source: ml/{os.path.basename(e['src'])} + a tuned config from ml/optimize.py.\n"
        "# Gate with `python test.py --gate --candidate <this> --incumbent main.py`\n"
        "# and a ladder read before promoting.\n\n"
    )
    footer = (
        "\n\n# ---- tuned configuration ----\n"
        f"_CONFIG = {cfg!r}\n"
        f"agent = {e['builder']}(_CONFIG)\n"
    )
    return header + src + footer


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("params", help="flat params JSON (from ml/optimize.py best.json)")
    ap.add_argument("--engine", default="v7", choices=list(_ENGINES))
    ap.add_argument("-o", "--out", default="main_ml.py")
    args = ap.parse_args()
    e = _ENGINES[args.engine]
    mod = __import__(e["spec"], fromlist=[e["default"]])
    params = {**getattr(mod, e["default"])(), **json.load(open(args.params))}
    open(args.out, "w", encoding="utf-8").write(build(params, args.engine))
    print(f"wrote {args.out}  ({os.path.getsize(args.out)} bytes)  engine={args.engine}")
    print("next: python test.py --gate --candidate", args.out, "--incumbent main.py --games 40")


if __name__ == "__main__":
    main()
