"""Flatten agents/main_v12.py + main.py into one self-contained main.py.

Root-causes the 123.2 ladder score for the earlier `main_v12.py` submission
(see docs/TOP10_TEARDOWN.md finding 2 / this session's investigation):
profiling ruled out a wall-clock timeout (max observed per-step latency was
~4-30ms even at the worst realistic field/hand size, ~30-200x under the 1s
budget). The far more likely cause is `docs/V12_IMPLEMENTATION.md`'s own
documented packaging trap: `main_v12.py` does `import main as v11`, so
naively renaming `main_v12.py` to `main.py` for submission makes it import
*itself* -- `v11.unlocked_cells` etc. then raise AttributeError every single
call (confirmed by reproduction), and the outer try/except silently falls
back to all-PASS for the entire game. That exactly matches "known-broken,
123.2" -- an idle agent that just sits on its starting $3000.

This script does the flatten `PLAN_LADDER_NEXT.md` always intended (concat
main.py's definitions, then main_v12.py's, with `v11.` call sites in the
v12 section rewritten to bare names since everything now lives in one
namespace) instead of a manual rename, so the trap can't recur.

    python tools/flatten_v12.py [--out main_v12_flat.py]

Always re-validate the output against a live, unflattened (main_v12.py +
main.py) run on a fixed seed before treating it as submittable -- see
tools/validate_flatten.py.
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def flatten(v11_src: str, v12_src: str) -> str:
    # Kaggle's loader (kaggle_environments/agent.py:get_last_callable) does
    # NOT look for a function literally named `agent` -- it execs the file
    # and takes the *last-inserted* callable in the module namespace dict:
    # `[v for v in env.values() if callable(v)][-1]`. Reassigning an
    # EXISTING dict key (like re-defining `agent`/`assign` a second time)
    # updates its value but does not move it to the end of insertion order.
    # v11's main.py defines both `agent` and `assign` first; naively
    # concatenating then lets v12 redefine those same two names, so neither
    # ends up last -- the actual last *new* name introduced is one of v12's
    # private helpers (observed: `_followup_bonus`), which Kaggle then calls
    # as if it were `agent()`, crashing every turn. This -- not a timeout --
    # is almost certainly what produced the 123.2 ladder score. Confirmed
    # both by reproducing the AttributeError from a naive rename-to-main.py
    # and by running this exact failure through kaggle_environments'
    # get_last_callable() directly (see tools/validate_flatten.py).
    #
    # Fix: rename v11's original top-level `agent` (and `assign`, belt and
    # braces) before concatenation, so v12's later `def agent(...)` /
    # `def assign(...)` are brand-new dict keys inserted at the true end.
    v11_src = re.sub(r"^def agent\(", "def _v11_agent_unused(", v11_src, flags=re.MULTILINE)
    v11_src = re.sub(r"^def assign\(", "def _v11_assign_unused(", v11_src, flags=re.MULTILINE)

    # Drop v12's own import of main.py and the (now redundant) stdlib import
    # main.py already needs; everything else from v12 is kept verbatim.
    body = v12_src
    body = re.sub(r"^import main as v11\s*\n", "", body, flags=re.MULTILINE)
    body = re.sub(r"^from collections import defaultdict\s*\n", "", body, flags=re.MULTILINE)
    # All cross-module calls in v12 were written as `v11.<name>` -- once both
    # files share one namespace those are just the bare global name. v12
    # never calls v11.agent or v11.assign (it reimplements both), so the
    # renames above don't need a matching call-site rewrite.
    body = re.sub(r"\bv11\.", "", body)

    banner = (
        '"""Kaggriculture main.py -- flattened v12 (v11 core + v12 executor).\n\n'
        "Generated by tools/flatten_v12.py from main.py + agents/main_v12.py.\n"
        "Do not hand-edit; regenerate from those sources instead.\n"
        '"""\n\n'
    )
    return banner + v11_src.rstrip() + "\n\n\n# ==== v12 executor (was agents/main_v12.py) ====\n\n" + body.lstrip()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--v11", default=str(ROOT / "main.py"))
    ap.add_argument("--v12", default=str(ROOT / "agents" / "main_v12.py"))
    ap.add_argument("--out", default=str(ROOT / "main_v12_flat.py"))
    args = ap.parse_args()

    v11_src = Path(args.v11).read_text(encoding="utf-8")
    v12_src = Path(args.v12).read_text(encoding="utf-8")
    out = flatten(v11_src, v12_src)
    Path(args.out).write_text(out, encoding="utf-8")
    print(f"wrote {args.out} ({len(out)} bytes)")


if __name__ == "__main__":
    main()
