"""Token / prompt accounting for the Kaggriculture Claude-Code sessions.

Reads the Claude Code session transcripts for this project and reports, per day
and per session:
  - user prompts sent (the thing the Pro plan actually rate-limits)
  - assistant turns
  - new tokens   = input + cache_creation + output   (the "fresh" cost)
  - cache_read   = context re-read from cache (cheap, but still usage)
  - total tokens = new + cache_read

Usage:
    python tools/token_report.py                # full history, writes experiments/TOKENS.md
    python tools/token_report.py --since 2026-09-01
    python tools/token_report.py --no-write     # print only

Pro plan note: there is no published per-day *token* number. The limiter is
"prompts per rolling 5-hour window" + a weekly cap. Check the live picture with
/status inside Claude Code. Use the "user prompts" column here as the proxy and
keep each agent version to a small prompt count.
"""

from __future__ import annotations

import argparse
import glob
import json
import os
from collections import defaultdict
from datetime import datetime

PROJECT_DIR = os.path.expanduser(
    r"~/.claude/projects/e--Competitions-Kaggriculture"
)
OUT_MD = os.path.join(os.path.dirname(__file__), "..", "experiments", "TOKENS.md")


def iter_records(path):
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue


def day_of(rec):
    ts = rec.get("timestamp")
    if not ts:
        return None
    try:
        return datetime.fromisoformat(ts.replace("Z", "+00:00")).date().isoformat()
    except ValueError:
        return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--since", help="YYYY-MM-DD, ignore days before this")
    ap.add_argument("--no-write", action="store_true", help="print only, don't touch TOKENS.md")
    args = ap.parse_args()

    # keyed by (day, session) -> counters
    agg = defaultdict(lambda: {
        "prompts": 0, "turns": 0,
        "new": 0, "cache_read": 0,
    })

    for path in sorted(glob.glob(os.path.join(PROJECT_DIR, "*.jsonl"))):
        session = os.path.splitext(os.path.basename(path))[0][:8]
        for rec in iter_records(path):
            day = day_of(rec)
            if not day:
                continue
            if args.since and day < args.since:
                continue
            rtype = rec.get("type")
            key = (day, session)
            if rtype == "user":
                # skip tool-result echoes: real user prompts have string content
                msg = rec.get("message", {})
                content = msg.get("content")
                is_tool_result = (
                    isinstance(content, list)
                    and any(isinstance(p, dict) and p.get("type") == "tool_result" for p in content)
                )
                if not is_tool_result:
                    agg[key]["prompts"] += 1
            elif rtype == "assistant":
                usage = rec.get("message", {}).get("usage", {})
                if not usage:
                    continue
                agg[key]["turns"] += 1
                agg[key]["new"] += (
                    usage.get("input_tokens", 0)
                    + usage.get("cache_creation_input_tokens", 0)
                    + usage.get("output_tokens", 0)
                )
                agg[key]["cache_read"] += usage.get("cache_read_input_tokens", 0)

    # roll up by day
    by_day = defaultdict(lambda: {"prompts": 0, "turns": 0, "new": 0, "cache_read": 0, "sessions": set()})
    for (day, session), c in agg.items():
        d = by_day[day]
        d["prompts"] += c["prompts"]
        d["turns"] += c["turns"]
        d["new"] += c["new"]
        d["cache_read"] += c["cache_read"]
        d["sessions"].add(session)

    lines = []
    lines.append("# Token / prompt log (auto-generated by tools/token_report.py)")
    lines.append("")
    lines.append(f"_Generated {datetime.now().isoformat(timespec='seconds')}_")
    lines.append("")
    lines.append("| Day | Sessions | User prompts | Asst turns | New tokens | Cache-read | Total |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|")
    tot = {"prompts": 0, "turns": 0, "new": 0, "cache_read": 0}
    for day in sorted(by_day):
        d = by_day[day]
        total = d["new"] + d["cache_read"]
        lines.append(
            f"| {day} | {len(d['sessions'])} | {d['prompts']} | {d['turns']} | "
            f"{d['new']:,} | {d['cache_read']:,} | {total:,} |"
        )
        for k in tot:
            tot[k] += d[k]
    grand = tot["new"] + tot["cache_read"]
    lines.append(
        f"| **all** | | **{tot['prompts']}** | **{tot['turns']}** | "
        f"**{tot['new']:,}** | **{tot['cache_read']:,}** | **{grand:,}** |"
    )
    lines.append("")
    lines.append("Per-session breakdown:")
    lines.append("")
    lines.append("| Day | Session | Prompts | Turns | New tokens | Total |")
    lines.append("|---|---|---:|---:|---:|---:|")
    for (day, session) in sorted(agg):
        c = agg[(day, session)]
        lines.append(
            f"| {day} | {session} | {c['prompts']} | {c['turns']} | "
            f"{c['new']:,} | {c['new'] + c['cache_read']:,} |"
        )

    report = "\n".join(lines) + "\n"
    print(report)
    if not args.no_write:
        os.makedirs(os.path.dirname(OUT_MD), exist_ok=True)
        with open(os.path.abspath(OUT_MD), "w", encoding="utf-8") as fh:
            fh.write(report)
        print(f"wrote {os.path.abspath(OUT_MD)}")


if __name__ == "__main__":
    main()
